package com.wartest.Client;


import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import java.text.*;

public class WebService1Client extends HttpServlet {
    private static final String CONTENT_TYPE = "text/html";

    /** Process the HTTP Get request */
    public void doGet(HttpServletRequest request, HttpServletResponse
            response) throws ServletException, IOException {
        response.setContentType(CONTENT_TYPE);
        PrintWriter out = response.getWriter();
        out.println("<h3>Choose favorite actor</h3>");
        out.println("<form method=\"GET\" action=" +
                "http://localhost:9999/cw/mov/>");
        out.println("Locale <select size=\"1\" name=\"actor\">");
        out.println("<option>yolo</option>");
	out.println("<option>Jensen Ackles</option>");
	out.println("<option>Andre 3000</option>");
	out.println("<option>Naveen Andrews</option>");
	out.println("<option>Jensen Atwood</option>");
	out.println("<option>Tyler Bachtel</option>");
	out.println("<option>Penn Badgley</option>");
	out.println("<option>Simon Baker</option>");
	out.println("<option>Christian Bale</option>");
	out.println("<option>Eric Balfour</option>");
	out.println("<option>Eric Bana</option>");
	out.println("<option>Alex Band</option>");
	out.println("<option>Antonio Banderas</option>");
	out.println("<option>Ike Barinholtz</option>");
	out.println("<option>Ben Barnes</option>");
	out.println("<option>Eugen Bauder</option>");
	out.println("<option>William Beckett</option>");
	out.println("<option>Tyson Beckford</option>");
	out.println("<option>David Beckham</option>");
	out.println("<option>Jason Behr</option>");
	out.println("<option>Jonathan Bennett </option>");
	out.println("<option>Sam Bennett </option>");
	out.println("<option>Dierks Bentley</option>");
	out.println("<option>Gael Garcia Bernal</option>");
	out.println("<option>Jon Bernthal</option>");
	out.println("<option>Wilson Bethel </option>");
	out.println("<option>Justin Bieber</option>");
	out.println("<option>David Blaine</option>");
	out.println("<option>James Blake</option>");
	out.println("<option>Corbin Bleu</option>");
	out.println("<option>Orlando Bloom</option>");
	out.println("<option>Jon Bon Jovi</option>");
	out.println("<option>Asher Book</option>");
	out.println("<option>David Boreanaz</option>");
	out.println("<option>Tom Bott</option>");
	out.println("<option>Raoul Bova</option>");
	out.println("<option>Bow Wow</option>");
	out.println("<option>Marlon Brando</option>");
	out.println("<option>Adam Brody</option>");
	out.println("<option>Chris Brown</option>");
	out.println("<option>Michel Brown</option>");
	out.println("<option>Justin Bruening</option>");
	out.println("<option>Austin Butler </option>");
	out.println("<option>Gerard Butler</option>");
	out.println("<option>Santiago Cabrera</option>");
	out.println("<option>Bobby Cannavale </option>");
	out.println("<option>Nick Cannon</option>");
	out.println("<option>Robert Carmine</option>");
	out.println("<option>Chris Carmack</option>");
	out.println("<option>Ryan Carnes</option>");
	out.println("<option>Anthony Catanzaro</option>");
	out.println("<option>Jim Caviezel</option>");
	out.println("<option>Henry Cavill</option>");
	out.println("<option>John Cena</option>");
	out.println("<option>Justin Chambers</option>");
	out.println("<option>David Charvet</option>");
	out.println("<option>Cesar Chiang</option>");
	out.println("<option>Chingy</option>");
	out.println("<option>Zachary Chitwood </option>");
	out.println("<option>Hayden Christensen</option>");
	out.println("<option>Michael Churchill</option>");
	out.println("<option>Eddie Cibrian</option>");
	out.println("<option>George Clooney</option>");
	out.println("<option>Ben Cohen</option>");
	out.println("<option>Harry Connick Jr.</option>");
	out.println("<option>Dane Cook</option>");
	out.println("<option>Anderson Cooper</option>");
	out.println("<option>Dominic Cooper</option>");
	out.println("<option>Michael Copon</option>");
	out.println("<option>Chris Cornell</option>");
	out.println("<option>Chace Crawford</option>");
	out.println("<option>Darren Criss</option>");
	out.println("<option>Russell Crowe</option>");
	out.println("<option>Tom Cruise</option>");
	out.println("<option>Francesco Cura'</option>");
	out.println("<option>Daddy Yankee</option>");
	out.println("<option>Matt Dallas </option>");
	out.println("<option>Matt Damon</option>");
	out.println("<option>Hugh Dancy</option>");
	out.println("<option>Marco Da Silva</option>");
	out.println("<option>Derrick Davenport</option>");
	out.println("<option>Eddie Davenport</option>");
	out.println("<option>Gabe David</option>");
	out.println("<option>Jeremy Davison</option>");
	out.println("<option>James Dean</option>");
	out.println("<option>Benicio Del Toro</option>");
	out.println("<option>Patrick Dempsey</option>");
	out.println("<option>Johnny Depp</option>");
	out.println("<option>Charles Dera</option>");
	out.println("<option>Alexandre Despatie</option>");
	out.println("<option>Aaron Diaz</option>");
	out.println("<option>Leonardo Dicaprio</option>");
	out.println("<option>Vin Diesel</option>");
	out.println("<option>Matt Dillon</option>");
	out.println("<option>Juan Dominic </option>");
	out.println("<option>Gary Dourdan</option>");
	out.println("<option>Drake</option>");
	out.println("<option>Andreas Drakenberg</option>");
	out.println("<option>Bryce Draper</option>");
	out.println("<option>George Dubovoi</option>");
	out.println("<option>Josh Duhamel</option>");
	out.println("<option>George Eads</option>");
	out.println("<option>Michael Ealy</option>");
	out.println("<option>Zac Efron</option>");
	out.println("<option>Elvis</option>");
	out.println("<option>Eminem</option>");
	out.println("<option>Michael Erwin</option>");
	out.println("<option>Chris Evans</option>");
	out.println("<option>Fabolous</option>");
	out.println("<option>Sean Faris</option>");
	out.println("<option>Evan Farmer</option>");
	out.println("<option>Colin Farrell</option>");
	out.println("<option>Oded Fehr</option>");
	out.println("<option>Tom Felton</option>");
	out.println("<option>Ralph Fiennes</option>");
	out.println("<option>Travis Fimmel</option>");
	out.println("<option>Trent Ford</option>");
	out.println("<option>Matthew Fox</option>");
	out.println("<option>Dave Franco</option>");
	out.println("<option>James Franco</option>");
	out.println("<option>Drew Fuller</option>");
	out.println("<option>David Fumero</option>");
	out.println("<option>Franky G</option>");
	out.println("<option>Adam Garcia</option>");
	out.println("<option>Andrew Garfield </option>");
	out.println("<option>Troy Garity</option>");
	out.println("<option>Louis Garrel</option>");
	out.println("<option>Teddy Geiger</option>");
	out.println("<option>Reynaldo Gianecchini</option>");
	out.println("<option>Cam Gigandet </option>");
	out.println("<option>Nicholas Gonzalez</option>");
	out.println("<option>Rick Gonzalez</option>");
	out.println("<option>Ryan Gosling</option>");
	out.println("<option>The Gotti Boys</option>");
	out.println("<option>Adrien Grenier</option>");
	out.println("<option>Ioan Gruffudd</option>");
	out.println("<option>Jake Gyllenhaal</option>");
	out.println("<option>Gale Harold</option>");
	out.println("<option>Josh Hartnett</option>");
	out.println("<option>Colton Haynes </option>");
	out.println("<option>Garrett Hedlund</option>");
	out.println("<option>Josh Henderson</option>");
	out.println("<option>David Henrie</option>");
	out.println("<option>Jay Hernandez</option>");
	out.println("<option>Tyler Hilton</option>");
	out.println("<option>Emile Hirsch</option>");
	out.println("<option>Josh Holloway</option>");
	out.println("<option>Marques Houston</option>");
	out.println("<option>Kris Humphries</option>");
	out.println("<option>Charlie Hunnam</option>");
	out.println("<option>Enrique Iglesias</option>");
	out.println("<option>Hugh Jackman</option>");
	out.println("<option>Jonathan Jackson</option>");
	out.println("<option>Thomas Jane</option>");
	out.println("<option>Ben Jelen</option>");
	out.println("<option>Derek Jeter</option>");
	out.println("<option>Avan Jogia</option>");
	out.println("<option>Aaron Johnson</option>");
	out.println("<option>Ben Patrick Johnson</option>");
	out.println("<option>Dwayne 'The Rock' Johnson</option>");
	out.println("<option>Rusty Joiner</option>");
	out.println("<option>Joe Jonas</option>");
	out.println("<option>Kevin Jonas</option>");
	out.println("<option>Nick Jonas </option>");
	out.println("<option>Wesley Jonathan</option>");
	out.println("<option>Steve Jones</option>");
	out.println("<option>Takeshi Kaneshiro</option>");
	out.println("<option>Gabe Kapler</option>");
	out.println("<option>Jordan Kaye</option>");
	out.println("<option>Gregory Keith</option>");
	out.println("<option>Toby Keith</option>");
	out.println("<option>Wiz Khalifa</option>");
	out.println("<option>Amir Khan</option>");
	out.println("<option>David Kimmerle</option>");
	out.println("<option>Taylor Kitsch</option>");
	out.println("<option>Johnny Knoxville</option>");
	out.println("<option>Boris Kodjoe</option>");
	out.println("<option>Lenny Kravitz</option>");
	out.println("<option>Ashton Kutcher</option>");
	out.println("<option>Shia LaBeouf</option>");
	out.println("<option>Nick Lachey</option>");
	out.println("<option>Caleb Lane</option>");
	out.println("<option>Taylor Lautner</option>");
	out.println("<option>Jude Law</option>");
	out.println("<option>Ryan LeBar</option>");
	out.println("<option>Samuel Le Bihan</option>");
	out.println("<option>Heath Ledger</option>");
	out.println("<option>Jared Leto</option>");
	out.println("<option>Adam Levine</option>");
	out.println("<option>Jason Lewis</option>");
	out.println("<option>LL Cool J</option>");
	out.println("<option>Laurent Lucas </option>");
	out.println("<option>Diego Luna</option>");
	out.println("<option>Kellan Lutz</option>");
	out.println("<option>Tobey Maguire</option>");
	out.println("<option>Rick Malambri</option>");
	out.println("<option>Rami Malek</option>");
	out.println("<option>Forbes March</option>");
	out.println("<option>Derek Marrocco</option>");
	out.println("<option>James Marsden</option>");
	out.println("<option>James Marsters</option>");
	out.println("<option>Ricky Martin</option>");
	out.println("<option>Olivier Martinez</option>");
	out.println("<option>Jesse McCartney</option>");
	out.println("<option>Matthew McConaughey</option>");
	out.println("<option>Neil McDonough </option>");
	out.println("<option>Ewan McGregor</option>");
	out.println("<option>Joey McIntyre </option>");
	out.println("<option>Julian McMahon</option>");
	out.println("<option>Johnny Messner</option>");
	out.println("<option>Jesse Metcalfe</option>");
	out.println("<option>Blake Michael</option>");
	out.println("<option>Frederic Michalak</option>");
	out.println("<option>Mika</option>");
	out.println("<option>Wentworth Miller</option>");
	out.println("<option>Sal Mineo</option>");
	out.println("<option>Jason Momoa</option>");
	out.println("<option>Christian Monzon</option>");
	out.println("<option>Shemar Moore</option>");
	out.println("<option>Carlos Moore</option>");
	out.println("<option>Matthew Morrison</option>");
	out.println("<option>Viggo Mortensen</option>");
	out.println("<option>Dermot Mulroney</option>");
	out.println("<option>Cillian Murphy</option>");
	out.println("<option>Chad Michael Murray</option>");
	out.println("<option>Nelly</option>");
	out.println("<option>Paul Newman</option>");
	out.println("<option>Joe Nichols</option>");
	out.println("<option>Amaury Nolasco</option>");
	out.println("<option>Dylan O'Brien</option>");
	out.println("<option>Omarion</option>");
	out.println("<option>Randy Orton</option>");
	out.println("<option>Clive Owen</option>");
	out.println("<option>Jared Padalecki</option>");
	out.println("<option>Hunter Parrish </option>");
	out.println("<option>Jason Patric</option>");
	out.println("<option>Marcus Patrick </option>");
	out.println("<option>Robert Pattinson</option>");
	out.println("<option>Sean Paul</option>");
	out.println("<option>Evan Peters</option>");
	out.println("<option>Alex Pettyfer</option>");
	out.println("<option>Ryan Phillippe</option>");
	out.println("<option>Joaquin Phoenix</option>");
	out.println("<option>River Phoenix</option>");
	out.println("<option>Chris Pine</option>");
	out.println("<option>Stefan Pinto</option>");
	out.println("<option>Romulo Pires</option>");
	out.println("<option>Brad Pitt</option>");
	out.println("<option>Michael Pitt</option>");
	out.println("<option>Raul Popa</option>");
	out.println("<option>Tyler Posey</option>");
	out.println("<option>Elvis Presley</option>");
	out.println("<option>Jason Priestley</option>");
	out.println("<option>Dominic Purcell</option>");
	out.println("<option>James Purefoy</option>");
	out.println("<option>Shawn Pyfrom</option>");
	out.println("<option>Sendhil Ramamurthy</option>");
	out.println("<option>Keanu Reeves</option>");
	out.println("<option>Steve Reeves</option>");
	out.println("<option>Simon Rex</option>");
	out.println("<option>Ryan Reynolds</option>");
	out.println("<option>Jonathan Rhys-Meyers</option>");
	out.println("<option>Patrick Ribbsaeter</option>");
	out.println("<option>Thiago Ribeiro </option>");
	out.println("<option>Caco Ricci</option>");
	out.println("<option>Tyson Ritter</option>");
	out.println("<option>Andy Roddick</option>");
	out.println("<option>Adam Rodriguez</option>");
	out.println("<option>Cristiano Ronaldo</option>");
	out.println("<option>Kenzie Roth</option>");
	out.println("<option>Brandon Routh</option>");
	out.println("<option>Mark Ruffalo</option>");
	out.println("<option>Mark Salling </option>");
	out.println("<option>Steve Sandvoss</option>");
	out.println("<option>Rodrigo Santoro</option>");
	out.println("<option>Alejo Sauras</option>");
	out.println("<option>Joseph Sayers</option>");
	out.println("<option>Marcus Schenkenberg</option>");
	out.println("<option>Dayton Schlosser </option>");
	out.println("<option>Robert Schwartzman </option>");
	out.println("<option>Seann William Scott </option>");
	out.println("<option>Frank Sepe</option>");
	out.println("<option>David Shaver</option>");
	out.println("<option>Ryan Sheckler</option>");
	out.println("<option>Shinya</option>");
	out.println("<option>Clement Sibony</option>");
	out.println("<option>Will Smith</option>");
	out.println("<option>Ian Somerhalder</option>");
	out.println("<option>Trey Songz</option>");
	out.println("<option>Soulja Boy</option>");
	out.println("<option>Hal Sparks</option>");
	out.println("<option>Scott Speedman</option>");
	out.println("<option>Edward Speleers</option>");
	out.println("<option>Jason Statham</option>");
	out.println("<option>Benjamin Stone</option>");
	out.println("<option>Richie Stringini</option>");
	out.println("<option>George Stults</option>");
	out.println("<option>Steven Strait</option>");
	out.println("<option>Daniel Sunjata</option>");
	out.println("<option>David Sutcliffe</option>");
	out.println("<option>Channing Tatum</option>");
	out.println("<option>Lucas Till </option>");
	out.println("<option>Justin Timberlake</option>");
	out.println("<option>Adam Tock</option>");
	out.println("<option>Sonny Tong </option>");
	out.println("<option>Stuart Townsend</option>");
	out.println("<option>Tyrese</option>");
	out.println("<option>Gaspard Ulliel</option>");
	out.println("<option>Karl Urban</option>");
	out.println("<option>Keith Urban</option>");
	out.println("<option>Brendon Urie</option>");
	out.println("<option>Usher</option>");
	out.println("<option>Wilmer Valderrama</option>");
	out.println("<option>Mark Valley</option>");
	out.println("<option>Drew Van Acker</option>");
	out.println("<option>Jean-Claude Van Damme</option>");
	out.println("<option>Mark Vanderloo</option>");
	out.println("<option>Mario Vasquez</option>");
	out.println("<option>Milo Ventimiglia</option>");
	out.println("<option>Eduardo Verastegui</option>");
	out.println("<option>Rafael Verga</option>");
	out.println("<option>Jason Wade</option>");
	out.println("<option>Mark Wahlberg</option>");
	out.println("<option>Matt Walch</option>");
	out.println("<option>Paul Walker</option>");
	out.println("<option>Denzel Washington</option>");
	out.println("<option>DeAndre Way </option>");
	out.println("<option>Tom Welling</option>");
	out.println("<option>Peter Wentz</option>");
	out.println("<option>Dominic West</option>");
	out.println("<option>Shane West</option>");
	out.println("<option>Pharrell Williams</option>");
	out.println("<option>Robbie Williams</option>");
	out.println("<option>Bruce Willis</option>");
	out.println("<option>Andreas Wilson</option>");
	out.println("<option>Jamie Wise</option>");
	out.println("<option>Ronnie Woo</option>");
	out.println("<option>Elijah Wood</option>");
	out.println("<option>Christian Yanik </option>");
	out.println("<option>Will Young</option>");
	out.println("<option>Nick Youngquest </option>");
	out.println("<option>Billy Zane</option>");
	out.println("<option>Kevin Zegers</option>");
	out.println("<option>Rob Zombie</option>");
        out.println("</select>");



        out.println("<p><input type=\"submit\" value=\"Submit\" >");
        out.println("<input type=\"reset\" value=\"Reset\"></p>");
        out.println("</form>");
        out.close(); // Close stream
    }



}

